#!/usr/bin/env python3

'''
print_packet

Prints a packet in an AjpForward Request
'''

import logging

from ajp4py import (AjpAttribute, AjpCommand, AjpForwardRequest, AjpHeader,
                    AjpRequestDirection)

if __name__ == '__main__':

  logging.basicConfig(
      level=getattr(
          logging,
          'DEBUG',
          None))

req = AjpForwardRequest(
    AjpRequestDirection.WEB_SERVER_TO_SERVLET_CONTAINER, 'localhost')
req.method = AjpCommand.GET
req.req_uri = '/docs/index.html'
req.remote_host = 'localhost'
req.add_request_header(AjpHeader.SC_REQ_ACCEPT, 'application/json')
req.add_request_header(AjpHeader.SC_REQ_USER_AGENT, 'ajp4py/v1.0')
req.add_request_header('X-Some-Other-Header', 'a value')
req.add_attribute(AjpAttribute.REMOTE_USER, 'user-name')
print(req.serialize_to_packet())
